concurrent = 10
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  limit = 5
  name = "Auto-scaled test runner 01"
  url = "https://gitlab.com/"
  token = "xxxxxxxxxxxxxxxxxx"
  executor = "docker+machine"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.machine]
    MaxGrowthRate = 1
    IdleCount = 2
    IdleTime = 60
    MachineDriver = "virtualbox"
    MachineName = "auto-scale-%s"
